
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 6;
  public static final int PAREN_FIN = 3;
  public static final int PAREN_INI = 2;
  public static final int error = 1;
  public static final int SIGNO_POR = 4;
  public static final int EOF = 0;
  public static final int SIGNO_MAS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAREN_INI",
  "PAREN_FIN",
  "SIGNO_POR",
  "SIGNO_MAS",
  "NUMERO"
  };
}

